## AND GATE

In [1]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[0],[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for AND GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

('iteration= ', 0, 'cost= ', 0.92443055)
('iteration= ', 1000, 'cost= ', 0.58530664)
('iteration= ', 2000, 'cost= ', 0.42811805)
('iteration= ', 3000, 'cost= ', 0.3417069)
('iteration= ', 4000, 'cost= ', 0.28696078)
('iteration= ', 5000, 'cost= ', 0.24858247)
('iteration= ', 6000, 'cost= ', 0.21981141)
('iteration= ', 7000, 'cost= ', 0.19724303)
('iteration= ', 8000, 'cost= ', 0.17896523)
('iteration= ', 9000, 'cost= ', 0.16380881)
('iteration= ', 10000, 'cost= ', 0.15100993)
('iteration= ', 11000, 'cost= ', 0.14004454)
('iteration= ', 12000, 'cost= ', 0.13053776)
Validating output for AND GATE
[[ 0.00623364]
 [ 0.13867456]
 [ 0.13747253]
 [ 0.80356979]]


## OR GATE

In [2]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

('iteration= ', 0, 'cost= ', 0.89822304)
('iteration= ', 1000, 'cost= ', 0.32833603)
('iteration= ', 2000, 'cost= ', 0.25695539)
('iteration= ', 3000, 'cost= ', 0.21035433)
('iteration= ', 4000, 'cost= ', 0.17733261)
('iteration= ', 5000, 'cost= ', 0.15281346)
('iteration= ', 6000, 'cost= ', 0.13394251)
('iteration= ', 7000, 'cost= ', 0.11900509)
('iteration= ', 8000, 'cost= ', 0.10691198)
('iteration= ', 9000, 'cost= ', 0.096939087)
('iteration= ', 10000, 'cost= ', 0.088586077)
('iteration= ', 11000, 'cost= ', 0.081497088)
('iteration= ', 12000, 'cost= ', 0.07541199)
Validating output for OR GATE
[[ 0.15863681]
 [ 0.93695617]
 [ 0.9389897 ]
 [ 0.99917632]]


## NOT GATE

In [3]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,1])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([1,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0],[1]])
op=np.array([[1],[0]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for NOT GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

('iteration= ', 0, 'cost= ', 0.64826626)
('iteration= ', 1000, 'cost= ', 0.32814068)
('iteration= ', 2000, 'cost= ', 0.21877509)
('iteration= ', 3000, 'cost= ', 0.16074553)
('iteration= ', 4000, 'cost= ', 0.12580545)
('iteration= ', 5000, 'cost= ', 0.10280137)
('iteration= ', 6000, 'cost= ', 0.086641707)
('iteration= ', 7000, 'cost= ', 0.074726321)
('iteration= ', 8000, 'cost= ', 0.065606311)
('iteration= ', 9000, 'cost= ', 0.058416981)
('iteration= ', 10000, 'cost= ', 0.052612931)
('iteration= ', 11000, 'cost= ', 0.047834359)
('iteration= ', 12000, 'cost= ', 0.043835096)
Validating output for NOT GATE
[[ 0.94851011]
 [ 0.03420143]]


## X-OR

In [10]:
import tensorflow as tf

x_ = tf.placeholder(tf.float32, shape=[4,2], name="x-input")
y_ = tf.placeholder(tf.float32, shape=[4,1], name="y-input")

w1 = tf.Variable(tf.random_uniform([2,2], -1, 1), name="weight1")
w2 = tf.Variable(tf.random_uniform([2,1], -1, 1), name="weight2")

Bias1 = tf.Variable(tf.zeros([2]), name="Bias1")
Bias2 = tf.Variable(tf.zeros([1]), name="Bias2")

A2 = tf.sigmoid(tf.matmul(x_, w1) + Bias1)
z = tf.sigmoid(tf.matmul(A2, w2) + Bias2)

cost = tf.reduce_mean(( (y_ * tf.log(z)) + ((1 - y_) * tf.log(1.0 - z)) ) * -1)
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cost)
XOR_X = [[0,0],[0,1],[1,0],[1,1]]
XOR_Y = [[0],[1],[1],[0]]

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for i in range(100000):
        sess.run(train_step, feed_dict={x_: XOR_X, y_: XOR_Y})
        if i % 5000 == 0:
            print('Iteration ', i)
            result=sess.run(z, feed_dict={x_: XOR_X, y_: XOR_Y})
            sess.run(w1)
            sess.run(Bias1)
            sess.run(w2)
            sess.run(Bias2)
print(result)

('Iteration ', 0)
('Iteration ', 5000)
('Iteration ', 10000)
('Iteration ', 15000)
('Iteration ', 20000)
('Iteration ', 25000)
('Iteration ', 30000)
('Iteration ', 35000)
('Iteration ', 40000)
('Iteration ', 45000)
('Iteration ', 50000)
('Iteration ', 55000)
('Iteration ', 60000)
('Iteration ', 65000)
('Iteration ', 70000)
('Iteration ', 75000)
('Iteration ', 80000)
('Iteration ', 85000)
('Iteration ', 90000)
('Iteration ', 95000)
[[ 0.02173987]
 [ 0.98282063]
 [ 0.98290873]
 [ 0.01905491]]


## X-NOR

In [12]:
import tensorflow as tf

x_ = tf.placeholder(tf.float32, shape=[4,2], name="x-input")
y_ = tf.placeholder(tf.float32, shape=[4,1], name="y-input")

w1 = tf.Variable(tf.random_uniform([2,2], -1, 1), name="weight1")
w2 = tf.Variable(tf.random_uniform([2,1], -1, 1), name="weight2")

Bias1 = tf.Variable(tf.zeros([2]), name="Bias1")
Bias2 = tf.Variable(tf.zeros([1]), name="Bias2")

A2 = tf.sigmoid(tf.matmul(x_, w1) + Bias1)
z = tf.sigmoid(tf.matmul(A2, w2) + Bias2)

cost = tf.reduce_mean(( (y_ * tf.log(z)) + ((1 - y_) * tf.log(1.0 - z)) ) * -1)
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cost)
XOR_X = [[0,0],[0,1],[1,0],[1,1]]
XOR_Y = [[1],[0],[0],[1]]

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for i in range(100000):
        sess.run(train_step, feed_dict={x_: XOR_X, y_: XOR_Y})
        if i % 5000 == 0:
            print('Iteration ', i)
            result=sess.run(z, feed_dict={x_: XOR_X, y_: XOR_Y})
            sess.run(w1)
            sess.run(Bias1)
            sess.run(w2)
            sess.run(Bias2)
print(result)

('Iteration ', 0)
('Iteration ', 5000)
('Iteration ', 10000)
('Iteration ', 15000)
('Iteration ', 20000)
('Iteration ', 25000)
('Iteration ', 30000)
('Iteration ', 35000)
('Iteration ', 40000)
('Iteration ', 45000)
('Iteration ', 50000)
('Iteration ', 55000)
('Iteration ', 60000)
('Iteration ', 65000)
('Iteration ', 70000)
('Iteration ', 75000)
('Iteration ', 80000)
('Iteration ', 85000)
('Iteration ', 90000)
('Iteration ', 95000)
[[ 0.98335212]
 [ 0.01550006]
 [ 0.0217476 ]
 [ 0.98592818]]
